### ISSUE TITLE
Letter C in brackets used instead of Copyright symbol

### ISSUE THREAD

**Issue by ADTC** [davidwernhart/AlDente-Charge-Limiter#962]
Just installed and trying out the app. I noticed the main settings window has `(C)` (i.e. uppercase letter C in brackets) instead of the copyright symbol, while the About dialog has the correct symbol. I thought it's perhaps missed out on. 🙂 

<img width="435" alt="image" src="https://github.com/davidwernhart/AlDente-Charge-Limiter/assets/6047296/7aeaa6d7-459d-446e-a7b3-ff829fad8f91">

**Comment by MatthiasKerbl** [comment]
Hi @ADTC,

Thanks again for letting us know. It is fixed in our newest version now.

Best,
Matthias

**Comment by ADTC** [comment]
Hmm thank you for fixing. Although, I'm on 1.22 and it's still the same (not fixed) 😆

<img width="205" alt="image" src="https://github.com/davidwernhart/AlDente-Charge-Limiter/assets/6047296/1cb62bab-782a-410a-b4cd-2095f2420e51">

Maybe the next version?

**Comment by MatthiasKerbl** [comment]
> Hmm thank you for fixing. Although, I'm on 1.22 and it's still the same (not fixed) 😆
> 
> <img alt="image" width="205" src="https://user-images.githubusercontent.com/6047296/249324574-1cb62bab-782a-410a-b4cd-2095f2420e51.png">
> Maybe the next version?

Hi @ADTC,

You are right, we missed it in the Free version. Will be fixed with the next update.

Best,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @ADTC,

This is fixed now with our newest update.

Best,
Matthias
